name: jetu
description: A new Flutter project.
publish_to: 'none'
version: 2.3.1+1

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_vector_icons: ^1.0.0
  yandex_mapkit: ^3.4.0
  yandex_geocoder: ^2.1.0
  firebase_analytics: ^10.0.4
  firebase_crashlytics: ^3.0.4
  firebase_core: ^2.1.1
  firebase_remote_config: ^3.0.4
  firebase_app_check: ^0.1.1+3
  firebase_core_platform_interface: 4.5.2
  nhost_storage_dart: ^1.0.0
  nhost_flutter_auth: ^3.0.0
  flutter_bloc: ^8.1.1
  shared_preferences: ^2.0.15
  image_picker: 1.0.2
  url_launcher: ^6.1.12
  mask: ^1.0.5
  fluttertoast: ^8.2.2
  pinput: ^3.0.0
  get_it: ^7.6.0
  mapbox_search: ^3.0.1+2
  supabase: ^1.11.0
  lottie: ^2.0.0
  store_redirect: 2.0.1
  app_version_update: ^4.0.1
  flutter_cupertino_date_picker_fork: ^1.0.7
  uuid: ^3.0.7


  routing_client_dart: ^0.3.1
  mapbox_api: ^1.0.0

  sliding_up_panel: ^2.0.0+1
  easy_debounce: ^2.0.2+1
  flutter_screenutil: ^5.8.4
  modal_bottom_sheet: ^3.0.0-pre
  flutter_local_notifications: 
  dio: ^4.0.6
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2

  # geo
  flutter_map: ^0.14.0
  # flutter_map_location_marker: ^3.1.0
  latlong2: ^0.8.1
  geolocator: ^11.0.0
  flutter_launcher_icons: ^0.13.1
  geocoding: ^2.0.5
  osm_nominatim: ^2.0.1
  firebase_messaging: ^14.2.1
  auto_route: ^5.0.4
  just_audio: ^0.9.33
  dotted_line: ^3.1.0
  flutter_svg: ^2.0.7
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: 2.3.3
  auto_route_generator: 5.0.3

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/images/
    - assets/icons/
    - assets/lottie/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraLight.ttf
        - asset: assets/fonts/Poppins-ExtraLightItalic.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
        - asset: assets/fonts/Poppins-LightItalic.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-SemiBoldItalic.ttf
        - asset: assets/fonts/Poppins-Thin.ttf
        - asset: assets/fonts/Poppins-ThinItalic.ttf

